version: '3'
services:
  api:
    build : ./django/
    restart: always
    networks:
     - frontend
     - backend-2
     - backend
    depends_on:
     - postgres
     - redis
    volumes:
     - api_data:/tmp
     - api_static_data:/django/static
  nginx:
    build : ./nginx/ 
    restart: always
    ports:
      - "80:80"
    networks:
     - frontend
    volumes:
     - api_data:/tmp
     - api_static_data:/gailvlun/static
    depends_on:
     - api
  postgres:
    restart: always
    build: ./postgres 
    networks:
     - backend
    volumes:
     - ./backups/postgres:/backups:rw
  redis:
    restart: always
    image: redis:latest
    expose:
     - "6379"
    networks:
     - backend-2
volumes:
   api_data:
   pgdata:
   api_static_data:

networks:
   frontend:
   backend-2:
   backend:
